Table Owner {
  id varchar pk
  name varchar
  license varchar
}

Table Branch{
  id varchar pk
  ownerId varchar 
  type varchar
  name varchar
  location varchar
  priceperunit integer
}
 
Table Room {
  id varchar pk
  brachId varchar
  number varchar
  capacity integer
  type varchar AC/NON AC
  ebApplicable bool
  rent integer
  ebReading integer
  ebUnits integer
  guests Array[]
}

Table Guest{
  id varchar pk
  roomId varchar
  branchId varchar
  name varchar
  phNo integer
  doj date
  dov date
  rentPaid bool
  adavance number
  advanceReturned bool
  ebPaid bool
  due Array[
    {month:jan,rent:true,eb:false},
    {month:feb,rent:true,eb:false},
  ]
}

Ref: Owner.id > Branch.ownerId
Ref: Branch.id > Room.brachId
Ref: Room.id > Guest.roomId

